# Documentation: http://docs.travis-ci.com/user/languages/julia/

codecov: true
coveralls: true
language: julia
julia:
  - 1.5

after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; Pkg.add("Coverage"); cd(Pkg.dir("Solaris")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; Pkg.add("Coverage"); cd(Pkg.dir("Solaris")); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  allow_failures:
  fast_finish: true
  include: